# See: https://github.com/artob/readmer#template-variables
---
label: Gitcache
title: Gitcache
summary:
  Gitcache mirrors Git repositories into a deduped pooled object store on top of Bitcache content-addressable storage.
